version: '3.4'
services:
  mysql:
    image: mysql:5.7
    container_name: ycp-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    networks:
      - mynet
  redis:
    container_name: ycp-redis
    image: redis:4-alpine
    ports:
      - "6379:6379"
    volumes:
      - './data/redis:/data'
    sysctls:
      net.core.somaxconn: 65535
    restart: always
    networks:
      - mynet
  redis-rebloom:
    image: 'redislabs/rebloom:latest'
    ports:
      - "16379:6379"
    volumes:
      - './data/sailredis:/data'
    restart: always
    networks:
      - mynet
networks:
  mynet:
    external: true