version: '3.4'
services:
  redis-master:
    image: redis:6.2.4
    volumes:
      - ./data/redis-master/data:/data
      - ./data/redis-master/logs:/logs
#    command:
#      # 服务启动
#      /bin/bash -c "redis-server --port 6379"
    ports:
      - "63790:6379"
    networks:
      - mynet
  redis-slave:
    image: redis:6.2.4
    volumes:
      - ./data/redis-slave/data:/data
      - ./data/redis-slave/logs:/logs
#    command:
#      # 服务启动
#      /bin/bash -c "redis-server --port 6379 --replicaof redis-master 63790"
    ports:
      - "63791:6379"
    networks:
      - mynet
    #依赖服务
    depends_on:
      - redis-master
networks:
  mynet:
    external: true